version: '3.8'

services:
  pagopa-checkout-auth-service:
    container_name: pagopa-checkout-auth-service
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - ./.env
    ports:
      - "8080:8080"