# Deploy to Azure Kubernetes Service:
# - DEV
# - UAT -> PROD
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

parameters:
  - name: "DEV_DEPLOY"
    displayName: "Deploy on DEV environment"
    type: boolean
    default: True
    values:
      - False
      - True
  - name: "UAT_PROD_DEPLOY"
    displayName: "Deploy on UAT environment with PROD promotion"
    type: boolean
    default: False
    values:
      - False
      - True
  - name: "SKIP_BUILD"
    displayName: "Check this flag to skip build and proceed to deploy a docker image previously built"
    type: boolean
    default: False
    values:
      - False
      - True
  - name: "RELEASE_SEMVER"
    displayName: "When packing a release, define the version bump to apply (release is done automatically when deploying on UAT and skipped on DEV) "
    type: string
    values:
      - major
      - minor
      - patch
      - none
    default: patch
  - name: "RELEASE_CHART_SEMVER"
    displayName: "When upgrading helm chart, define the version bump to apply"
    type: string
    values:
      - major
      - minor
      - patch
    default: patch
  - name: "FORCE_REPLACE_DOCKER_IMAGE"
    displayName: "Force the existing docker image to be replaced (latest tag)"
    type: boolean
    default: False
    values:
      - False
      - True
  - name: "SKIP_RELEASE"
    displayName: "Skip release"
    type: boolean
    default: False
    values:
      - False
      - True
  - name: "UAT_SKIP_BLUE_DEPLOYMENT"
    displayName: "Skip blue/green UAT deployment strategy: activating this parameter no blue version will be created and the pipeline proceed building and deploy artifact green version"
    type: boolean
    default: True
    values:
      - False
      - True
  - name: "PROD_SKIP_BLUE_DEPLOYMENT"
    displayName: "Skip blue/green PROD deployment strategy: activating this parameter no blue version will be created and the pipeline proceed building and deploy artifact green version"
    type: boolean
    default: True
    values:
      - False
      - True
  - name: "NATIVE_COMPILATION"
    displayName: "Boolean flag to use native compilation or JVM runtime for the output executable: activating this parameter native compilation will be used, jvm otherwise"
    type: boolean
    default: True
    values:
      - False
      - True

resources:
  repositories:
    - repository: pagopaCommons
      type: github
      name: pagopa/azure-pipeline-templates
      ref: refs/tags/v6.14.0
      endpoint: "io-azure-devops-github-ro"
    - repository: pagopaCheckoutTests
      type: github
      name: pagopa/pagopa-checkout-tests
      ref: main
      endpoint: "io-azure-devops-github-ro"

pool:
  vmImage: ubuntu-latest

variables:
  - ${{ if eq(parameters['NATIVE_COMPILATION'], True) }}:
    - name: DOCKER_FILE_NAME
      value: "Dockerfile.native"
    - name: DOCKER_FILE_VERSION_SUFFIX
      value: ""
  - ${{ else }}:
    - name: DOCKER_FILE_NAME
      value: "Dockerfile.jvm"
    - name: DOCKER_FILE_VERSION_SUFFIX
      value: "-jvm"

stages:
  # --- START Deploy UAT --- #
  - stage: "Build_release_candidate"
    displayName: "Build release candidate"
    dependsOn: []
    jobs:
      - job: "build"
        displayName: "Build release candidate docker image"
        steps:
          - template: templates/docker-release/template.yaml@pagopaCommons
            parameters:
              CONTAINER_REGISTRY_SERVICE_CONN: $(UAT_CONTAINER_REGISTRY_SERVICE_CONN)
              CONTAINER_REGISTRY_FQDN: $(UAT_CONTAINER_NAMESPACE)
              DOCKER_IMAGE_NAME: $(K8S_IMAGE_REPOSITORY_NAME)
              DOCKER_IMAGE_TAG: $(Build.SourceVersion)${{ variables.DOCKER_FILE_VERSION_SUFFIX }}
              FORCE_REPLACE_DOCKER_IMAGE: ${{ parameters.FORCE_REPLACE_DOCKER_IMAGE }}
              ${{ if eq(parameters['NATIVE_COMPILATION'], True) }}:
                DOCKERFILE: Dockerfile.native
              ${{ else }}:
                DOCKERFILE: Dockerfile.jvm
          - template: azure-templates/chart-current-version.yml

  - stage: Release
    dependsOn: Build_release_candidate
    jobs:
      - job: make_release
        displayName: Make github release
        steps:
          - template: azure-templates/chart-current-version.yml

  - stage: "tag_docker_release"
    displayName: "Tag Docker image to be release"
    dependsOn: Release
    condition: and(
      succeeded(),
      ne('${{parameters.RELEASE_SEMVER}}', 'none')
      )
    variables:
      app_version: perf
    jobs:
      - job: "build"
        displayName: "Build UAT service beta"
        steps:
          - task: Docker@2
            displayName: "docker login"
            inputs:
              containerRegistry: $(UAT_CONTAINER_REGISTRY_SERVICE_CONN)
              command: "login"
          - task: Bash@3
            displayName: "docker tag new version"
            inputs:
              targetType: "inline"
              script: |
                docker pull $(UAT_CONTAINER_NAMESPACE)/$(K8S_IMAGE_REPOSITORY_NAME):$(Build.SourceVersion)${{ variables.DOCKER_FILE_VERSION_SUFFIX }}
                docker tag $(UAT_CONTAINER_NAMESPACE)/$(K8S_IMAGE_REPOSITORY_NAME):$(Build.SourceVersion)${{ variables.DOCKER_FILE_VERSION_SUFFIX }} $(UAT_CONTAINER_NAMESPACE)/$(K8S_IMAGE_REPOSITORY_NAME):$(app_version)${{ variables.DOCKER_FILE_VERSION_SUFFIX }}
                docker push $(UAT_CONTAINER_NAMESPACE)/$(K8S_IMAGE_REPOSITORY_NAME):$(app_version)${{ variables.DOCKER_FILE_VERSION_SUFFIX }}

  - stage: "Deploy_UAT_Blue"
    displayName: "UAT blue deployment"
    dependsOn: [tag_docker_release, Release]
    condition: |
      and(
        eq(${{parameters.UAT_PROD_DEPLOY}}, true),
        in(dependencies.tag_docker_release.result, 'Succeeded', 'Skipped'),
        in(dependencies.Release.result, 'Succeeded', 'Skipped')
      )
    variables:
      app_version: perf
    jobs:
      - deployment: "Blue_deployment"
        displayName: "Blue deployment"
        pool:
          name: pagopa-uat-linux
        environment: "UAT"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  displayName: "Checkout"
                - task: KubectlInstaller@0
                - task: Bash@3
                  name: update_chart_version
                  displayName: "Setup helm microservice chart"
                  inputs:
                    targetType: "inline"
                    script: |
                      helm repo add microservice-chart https://pagopa.github.io/aks-microservice-chart-blueprint
                      helm dep build helm
                - template: azure-templates/helm-microservice-chart-deploy.yml
                  parameters:
                    DO_DEPLOY: true
                    DO_BLUE_GREEN_DEPLOY: true
                    ENV: "UAT"
                    KUBERNETES_SERVICE_CONN: $(UAT_KUBERNETES_SERVICE_CONN)
                    NAMESPACE: checkout
                    APP_NAME: soak-beta-$(K8S_IMAGE_REPOSITORY_NAME)
                    VALUE_FILE: "helm/values-uat.yaml"
                    GREEN_VERSION: $(app_version)${{ variables.DOCKER_FILE_VERSION_SUFFIX }}
                    BLUE_VERSION: $(app_version)${{ variables.DOCKER_FILE_VERSION_SUFFIX }}
                    #for jvm build add --values option targeting containing overrides from native helm values, such as required resources etc
                    ${{ if eq(parameters['NATIVE_COMPILATION'], False) }}:
                      ARGUMENTS: "--timeout 5m0s --values helm/valuesOverrides/overrides-jvm-uat.yaml"

  - stage: "API_UAT_test_blue"
    displayName: "Running API test on UAT (Blue instance)"
    dependsOn: Deploy_UAT_Blue
    condition: eq(dependencies.Deploy_UAT_Blue.result, 'Succeeded')
    jobs:
      - job: newman_api_test
        steps:
          - checkout: pagopaCheckoutTests
          - template: azure-templates/api-tests.yml
            parameters:
              API_TEST_FILE: "api-tests/auth-service-tests/auth-service-api.tests.json"
              ENV_FILE: "api-tests/uat.envs.json"
              TEST_FILE_PREFIX: "uat"

  - stage: "GreenDeployment_WaitForApproval"
    displayName: "UAT green approval deployment"
    dependsOn: [API_UAT_test_blue, tag_docker_release, Release]
    condition: |
      and(
        eq(${{parameters.UAT_PROD_DEPLOY}}, true),
        in(dependencies.API_UAT_test_blue.result, 'Succeeded', 'Skipped','Failed'),
        in(dependencies.tag_docker_release.result, 'Succeeded'),
      )
    variables:
      commitUrl: $[ stageDependencies.Release.build.outputs['chart_current_version.commitUrl'] ]
    jobs:
      - job: GreenDeployment_WaitForApproval
        displayName: Manual blue deploy approval
        pool: server
        timeoutInMinutes: 4320 # 3 days
        steps:
          - task: ManualValidation@0
            timeoutInMinutes: 4320 # 3 days
            inputs:
              notifyUsers: $(APPROVE_TOUCHPOINT_MAIL)
              instructions: "Please approve or reject UAT blue green promotions for $(commitUrl)"
              onTimeout: "reject"

  - stage: "Deploy_UAT_Green"
    displayName: "UAT green deployment"
    dependsOn: [GreenDeployment_WaitForApproval, tag_docker_release, Release]
    condition: |
      and(
        eq(${{parameters.UAT_PROD_DEPLOY}}, true),
        in(dependencies.tag_docker_release.result, 'Succeeded', 'Skipped'),
        in(dependencies.GreenDeployment_WaitForApproval.result, 'Succeeded', 'Skipped'),
        in(dependencies.Release.result, 'Succeeded', 'Skipped'),
      )
    variables:
      app_version: perf
    jobs:
      - deployment: "Green_deployment"
        displayName: "Green deployment"
        pool:
          name: pagopa-uat-linux
        environment: "UAT"
        strategy:
          runOnce:
            deploy:
              steps:
                # uninstall helm release used for blue instance
                - task: HelmDeploy@0
                  displayName: Un-install UAT blue version
                  continueOnError: true
                  inputs:
                    kubernetesServiceEndpoint: $(UAT_KUBERNETES_SERVICE_CONN)
                    namespace: checkout
                    command: uninstall
                    arguments: soak-beta-$(K8S_IMAGE_REPOSITORY_NAME)
                - checkout: self
                  displayName: "Checkout"
                - task: KubectlInstaller@0
                - task: Bash@3
                  name: update_chart_version
                  displayName: "Setup helm microservice chart"
                  inputs:
                    targetType: "inline"
                    script: |
                      helm repo add microservice-chart https://pagopa.github.io/aks-microservice-chart-blueprint
                      helm dep build helm
                - template: azure-templates/helm-microservice-chart-deploy.yml
                  parameters:
                    DO_DEPLOY: true
                    DO_BLUE_GREEN_DEPLOY: false
                    ENV: "UAT"
                    KUBERNETES_SERVICE_CONN: $(UAT_KUBERNETES_SERVICE_CONN)
                    NAMESPACE: checkout
                    APP_NAME: soak-$(K8S_IMAGE_REPOSITORY_NAME)
                    VALUE_FILE: "helm/values-uat.yaml"
                    GREEN_VERSION: $(app_version)${{ variables.DOCKER_FILE_VERSION_SUFFIX }}
                    #for jvm build add --values option targeting containing overrides from native helm values, such as required resources etc
                    ${{ if eq(parameters['NATIVE_COMPILATION'], False) }}:
                      ARGUMENTS: "--timeout 5m0s --values helm/valuesOverrides/overrides-jvm-uat.yaml"

  - stage: "API_UAT_test_green"
    displayName: "Running API test on UAT green"
    dependsOn: Deploy_UAT_Green
    condition: eq(dependencies.Deploy_UAT_Green.result, 'Succeeded')
    jobs:
      - job: newman_api_test
        steps:
          - checkout: pagopaCheckoutTests
          - template: azure-templates/api-tests.yml
            parameters:
              API_TEST_FILE: "api-tests/auth-service-tests/auth-service-api.oneidentity.tests.json"
              ENV_FILE: "api-tests/uat.envs.json"
              TEST_FILE_PREFIX: "uat"

  # --- END Deploy UAT --- #
