openapi: 3.0.3
info:
  title: OI Essential OIDC Endpoints - OpenAPI 3.0
  description: |-
    Essential OneIdentity OpenID Connect endpoints for authentication flow

    Some useful links:
    - [One Identity repository](https://github.com/pagopa/oneidentity)
    - [The source API definition for OI](https://github.com/pagopa/oneidentity/blob/c2b7f398d36a0f259685e785c8f5a6b80ba8b9eb/src/infra/api/oi.tpl.json)
  termsOfService: http://pagopa.it/terms/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
externalDocs:
  description: Find out more about OI
  url: https://pagopa.it
servers:
  - url: ${server_url}

paths:
  /oidc/token:
    post:
      tags:
        - Token Server APIs
      description: 'Request access_token or refresh_token using OAuth 2.0 grant_type: password authorization_code refresh_token client_credentials urn:ietf:params:oauth:grant-type:jwt-bearer urn:ietf:params:oauth:grant-type:saml2-bearer. See RFC 6749 for more details.'
      operationId: createRequestToken
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - code
                - redirect_uri
                - grant_type
              properties:
                redirect_uri:
                  type: string
                  description: Required if grant_type is authorization_code. Must contain a valid auth code
                code:
                  type: string
                  description: Required if grant_type is authorization_code
                grant_type:
                  type: string
                  description: 'For grant_type=authorization_code: client_id, client_secret, code, and redirect_uri are required.'
                  enum:
                    - authorization_code
                  default: authorization_code
      parameters:
        - name: authorization
          in: header
          required: true
          description: 'The HTTP basic authorization header containing the client credentials as base64 encoded string (authorization: Basic base64(client_id:client_secret)). This can only be used INSTEAD of the parameters ''client_id'', ''client_secret''.'
          schema:
            type: string
      responses:
        "200":
          $ref: '#/components/responses/authToken200'
        "400":
          $ref: '#/components/responses/badRequest'
        "401":
          $ref: '#/components/responses/unauthorized'
        "403":
          $ref: '#/components/responses/forbidden'
        "500":
          $ref: '#/components/responses/serverError'
  /oidc/keys:
    get:
      tags:
        - Token Server APIs
      operationId: Get_jwk_set_
      description: This endpoint implements the JWKS_URI as specified at http://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata
      x-amazon-apigateway-integration:
        type: HTTP_PROXY
        httpMethod: GET
        uri: ${uri}/oidc/keys
        connectionType: VPC_LINK
        connectionId: ${connection_id}
        requestParameters: {}
        responses:
          '200':
            statusCode: '200'
            requestParameters: {}
          '403':
            statusCode: '403'
            requestParameters: {}
          '405':
            statusCode: '405'
            requestParameters: {}
          '500':
            statusCode: '500'
            requestParameters: {}
      responses:
        '200':
          description: JWK set containing public keys that enable clients to validate a JSON Web Token (JWT) issued by this OpenID Connect Provider
          content:
            application/json:
              schema:
                type: object
                properties:
                  keys:
                    type: array
                    items:
                      type: object
                      additionalProperties:
                        type: string
                    example:
                      - kty: RSA
                        kid: default_ssl_key
                        use: sig
                        'n': 58BezRBeYOM3rOo1vcllcLc8QAwz6AmQj4EvGUqATMUz4bfYJ9Lf2wb9xCQhSLSkndfFAF5V754G0mRelBGK7yIja-M-EBXoJeT3nvwA46g7MkZGf11uP2dz2k4CkLdFHnlGzvuLQVBQpqbz-O_hFfEDxBk9zV4shR8O_iGv4fDi0dNHZfXzxkr_iH8Oj2qQeZFvv61I4RffeNmx04lYea2KFsF_8rWDlENWAr8RbqpY_y5lbxgC_xyBunTkoIEommqz55ZFIcklYerJUVSeIA90KMyM60wZh0JF_T5kuXEs-3AWh8Bkx-sVE2hu5S5x4_lADsPojLwWTT7or_sw9Q
                        e: AQAB
                    description: JWK set in JSON array format
        '403':
          $ref: '#/components/responses/forbidden'
        '405':
          $ref: '#/components/responses/methodNotAllowed'
        '429':
          $ref: '#/components/responses/rateLimit'
        '500':
          $ref: '#/components/responses/serverError'
      summary: OpenID Connect jwks endpoint
components:
  responses:
    authToken200:
      description: A success response that includes the issued token, expire and other details from the OAuth Server
      headers:
        Pragma:
          description: Pragma browser directive
          schema:
            type: string
            default: no-cache
        Cache-Control:
          description: Cache-Control browser directive
          schema:
            type: string
            default: no-store
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TokenData'
    badRequest:
      description: Bad request
      headers:
        Pragma:
          description: Pragma browser directive
          schema:
            type: string
            default: no-cache
        Cache-Control:
          description: Cache-Control browser directive
          schema:
            type: string
            default: no-store
        content-type:
          description: Content type response.
          schema:
            type: string
    unauthorized:
      description: The client could not be authenticated.
      headers:
        Pragma:
          description: Pragma browser directive
          schema:
            type: string
            default: no-cache
        Cache-Control:
          description: Cache-Control browser directive
          schema:
            type: string
            default: no-store
        content-type:
          description: Content type response.
          schema:
            type: string
    forbidden:
      description: Forbidden.
      headers:
        Pragma:
          description: Pragma browser directive
          schema:
            type: string
            default: no-cache
        Cache-Control:
          description: Cache-Control browser directive
          schema:
            type: string
            default: no-store
        content-type:
          description: Content type response.
          schema:
            type: string
    serverError:
      description: unknown error
      headers:
        Pragma:
          description: Pragma browser directive
          schema:
            type: string
            default: no-cache
        Cache-Control:
          description: Cache-Control browser directive
          schema:
            type: string
            default: no-store
        content-type:
          description: Content type response.
          schema:
            type: string
    methodNotAllowed:
      description: The HTTP method is not valid
      headers:
        Allow:
          description: This header is required by RFC 2616 and contains a comma separated list of valid HTTP methods.
          schema:
            type: string
            default: GET
        Pragma:
          description: Pragma browser directive
          schema:
            type: string
            default: no-cache
        Cache-Control:
          description: Cache-Control browser directive
          schema:
            type: string
            default: no-store
    rateLimit:
      description: Too many requests
      headers:
        Pragma:
          description: Pragma browser directive
          schema:
            type: string
            default: no-cache
        Cache-Control:
          description: Cache-Control browser directive
          schema:
            type: string
            default: no-store
  schemas:
    TokenData:
      type: object
      properties:
        access_token:
          type: string
          description: The Access Token for the given token request
        token_type:
          type: string
          description: The Token Type issued
          example: Bearer
        expires_in:
          type: string
          description: The expiry time, in seconds
          example: "3600"
        refresh_token:
          type: string
          description: The refresh token, if applicable
        scope:
          type: string
          description: The issued scope
          example: oob
        id_token:
          type: string
          description: If the requested SCOPE included 'msso' or 'openid', response includes an id_token
        id_token_type:
          type: string
          description: If the requested SCOPE included 'msso' or 'openid', response includes an id_token_type
      title: TokenData