microservice-chart:
  namespace: "checkout"
  nameOverride: ""
  fullnameOverride: "beta-pagopa-checkout-auth-service"
  image:
    repository: pagopaucommonacr.azurecr.io/pagopacheckoutauthservice
    tag: "0.9.2"
    pullPolicy: Always
  livenessProbe:
    handlerType: httpGet
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 5
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    handlerType: httpGet
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 5
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress:
    create: true
    host: "weuuat.checkout.internal.uat.platform.pagopa.it"
    path: /beta/pagopa-checkout-auth-service/(.*)
    servicePort: 8080
  serviceAccount:
    name: "checkout-workload-identity"
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - all
  resources:
    requests:
      memory: "256Mi"
      cpu: "150m"
    limits:
      memory: "256Mi"
      cpu: "150m"
  autoscaling:
    enable: false
    minReplica: 1
    maxReplica: 1
    pollingInterval: 30 # seconds
    cooldownPeriod: 30 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "70"
  envConfig:
    DEFAULT_LOGGING_LEVEL: "info"
    APP_LOGGING_LEVEL: "info"
    WEB_LOGGING_LEVEL: "info"
    ECS_SERVICE_NAME: "pagopa-checkout-auth-service"
    ECS_SERVICE_ENVIRONMENT: "uat"
    OTEL_RESOURCE_ATTRIBUTES: "service.name=pagopa-checkout-auth-service,deployment.environment=uat"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-system.svc:4317"
    OTEL_LOGS_EXPORTER: none
    OTEL_TRACES_SAMPLER: "always_on"
    ONE_IDENTITY_BASE_URL: "https://api.uat.platform.pagopa.it/checkout/identity-provider-mock/v1"
    ONE_IDENTITY_REDIRECT_URI: "http://uat.checkout.pagopa.it/auth-callback"
    ONE_IDENTITY_CLIENT_ID: "DlBY1GBNsl-w33g8Cpi1MXaMFNCxxvgg0KQPhEvmZ4I"
    REDIS_PORT: "6380"
    REDIS_SSL_ENABLED: "true"
    AUTHENTICATED_USER_SESSION_CACHE_TTL_SECONDS: "1800" #30 minutes
    OIDC_AUTH_STATE_CACHE_TTL_SECONDS: "300" #5 minutes
    OIDC_KEYS_CACHE_TTL_SECONDS: "3600" # 1 hour
    ONE_IDENTITY_SERVER_URI: "https://weuuat.checkout.internal.uat.platform.pagopa.it/pagopa-checkout-identity-provider-mock/"
    ONE_IDENTITY_SERVER_READ_TIMEOUT_MILLIS: "10000"
    ONE_IDENTITY_SERVER_CONNECTION_TIMEOUT_MILLIS: "10000"
    SESSION_TOKEN_LENGTH_IN_BYTES: "16"
  envSecret:
    OTEL_EXPORTER_OTLP_HEADERS: elastic-otel-token-header
    REDIS_HOST: redis-checkout-hostname
    REDIS_PASSWORD: redis-checkout-access-key
    ONE_IDENTITY_CLIENT_SECRET: checkout-one-identity-client-secret
  keyvault:
    name: "pagopa-u-checkout-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  secretProviderClass:
    secretProviderClass:
      create: false
  azure:
    workloadIdentityClientId: "61f9e998-9676-42fa-9435-554586259190"
