name: Semantic versioning

on:
  push:
    branches: [ "CHK-4016-fix-app-version" ]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  semver-update:
    name: Update semver for every eligible file of repo (helm charts, gradle files, etc.)
    runs-on: ubuntu-latest
    outputs:
      semver: ${{ steps.get_new_ver.outputs.version }}
    steps:
      - name: Setup git author
        run: |
          git config --global user.email "${{ secrets.GIT_EMAIL }}" && git config --global user.name "${{ secrets.GIT_USERNAME }}"
      - name: Checkout release branch
        uses: actions/checkout@v2
        with:
          ref: 'CHK-4016-fix-app-version'
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
      - name: Get new gradle version
        id: get_new_ver
        run: |
          ./gradlew help incrementVersion --versionIncrementType=patch 
          version=$(./gradlew printVersion -Psnapshot=false  -q | head -n1 | cut -d' ' -f2)
          git add build.gradle.kts
          echo $version
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Update Helm Version Values
        run: |
          for i in helm/values-*.yaml; do
            [ -f "$i" ] || break
            yq -i ".microservice-chart.image.tag = \"$(steps.get_new_ver.outputs.version)\"" "$i"
            git add "$i"
          done
      - name: Update Chart App Version
        run: |
          CHART_FILE="helm/Chart.yaml"
            if [[ -f "$CHART_FILE" ]]; then
              yq -i ".appVersion = \"$(steps.get_new_ver.outputs.version)\"" "$CHART_FILE"
              git add "$CHART_FILE"
          fi
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Install semver globally
        run: yarn global add semver
      - name: Update Chart Version
        run: |
          RELEASE_CHART_SEMVER= patch
          CHART_FILE="helm/Chart.yaml"
          CURRENT_CHART_VERSION=$(yq -r '.version' $CHART_FILE)
          if [[ -f "$CHART_FILE" ]]; then
            yq -i ".version = \"$(semver $CURRENT_CHART_VERSION -i $RELEASE_CHART_SEMVER )\"" "$CHART_FILE"
            git add "$CHART_FILE"
          fi
      - name: Push New Version
        run: |
          git status
          git commit -m "Bump version [skip ci]"
          git push origin CHK-4016-fix-app-version