name: Semantic versioning

on:
  push:
    branches: [ "CHK-4016-fix-app-version" ]

permissions:
  contents: write

jobs:
  semver-update:
    name: Update semver for every eligible file of repo (helm charts, gradle files, etc.)
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Set up JDK 21
        id: getNewAppVersion
        uses: actions/setup-java@v3
        with:
          java-version: '21'
      - name: Run Gradle task
        run: |
          echo "version=./gradlew help --incrementVersion --versionIncrementType=patch" >> $GITHUB_OUTPUT
          echo $version